name: Hola Mundo

on: [push] # evento: cuando hacemos push en nuestro repositorio

jobs: # nos va a permitir ejecutar todo lo que necesitamos dentro de algún servidor
  # los jobs se ejecutan directamente dentro de un servidor, y action nos provee varios servidores (mac, ubuntu, etc)
  hola: # damos un nombre representativo
    runs-on: ubuntu-latest # con runs-on especificamos el sistema operativo en el que queremos ejecutar el job. en este caso seleccionamos ubuntu en su ultima versión

    steps: # definimos a los steps, que son la unidad mas pequeña, que nos van a permitir realizar diferentes acciones
      # definimos todos los steps que necesitamos (una lista de esteps):
      - name: Hola Mundo # nombre de la lista
        run: echo "Hola Mundo" # run nos permite ejecutar un comando

      # podemos agregar mas steps
      - name: touch file
        run: touch hola.txt

      - name: Set text
        run: echo "Hola Mundo" >> hola.txt

      - name: Read file
        run: cat hola.txt

  other:
    runs-on: ubuntu-latest # cada job se ejecuta dentro de un servidor, por eso se debe definir run on en cada jon
    needs: hola # generamos una dependencia para que este job se ejecute despues del job hola

    steps:
      - name: LS # nombre del step
        run: ls -al
